### PR TITLE
Added binary data stream option

### PR DESCRIPTION
**Pull request by Matlar**
Some small fixes on the server as well as a new option to send the images using a binary data stream instead of using a form. Not sure how you usually resolve merge-conflicts or how to see the differences, but I am pretty sure it's just a small thing regarding where the dots before the file extensions are added.

### CODE REVIEW

**Comment by Matlar** [comment]
I think I resolved all the conflicts now. Still weird how some of the old commits are reappearing though.

**Comment by Matlar** [comment]
Added the basic neural network commit

**Comment by gustavung** [comment]
Don't worry about the duplicate commits, it can be fixed with an interactive rebase later!

**Review by gustavung — APPROVED** [review]
LGTM, okay apparently not...

**Review by gustavung — CHANGES_REQUESTED** [review]
rebase and fix merge conflicts!

**Comment by angloth** [comment]
Hey guys check out my github repo: https://github.com/johnnil/Lifelink

**Comment by gustavung** [comment]
Closed due to #32. @angloth go home peasant

**Pull request closed without merging**
